--- 
version: '3'

services: 
  php-fpm: 
    build: 
      context: ./php-fpm
    depends_on: 
      - mysql
    links:
      - mysql
    expose: 
      - "9000"
    volumes: 
      - "./www:/var/www/html"
    restart: always
  nginx: 
    build: ./nginx
    ports: 
      - "24285:80"
      - "4443:443"
    volumes: 
      - "./www:/var/www/html"
    depends_on: 
      - php-fpm
    restart: always
  mysql: 
    build: ./mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=h9tGyYgsTFP7
    ports: 
      - "34014:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /init-database.sql
    volumes: 
      - "./mysql/data:/var/lib/mysql"
    restart: always
volumes: 
  mysql-data:
